//Trash button
//  <button
// className="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 dark:bg-red-600 dark:hover:bg-red-700 focus:outline-none dark:focus:ring-red-800"
// >
// <FontAwesomeIcon icon={faTrash} />
// </button>
  

//Filtering button 
//   <div className="relative">
//   <button
//     id="dropdownDefaultButton"
//     onClick={toggleDropdown}
//     className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
//     type="button"
//   >
//     {selectedRole} {/* Directly show the selected role */}
//     <svg className="w-2.5 h-2.5 ms-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
//       <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="m1 1 4 4 4-4" />
//     </svg>
//   </button>

//   {dropdownOpen && (
//     <div id="dropdown" className="absolute right-0 z-10 bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
//       <ul className="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefaultButton">
//         <li>
//           <button 
//             onClick={() => handleRoleSelect('All')} 
//             className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
//           >
//             All
//           </button>
//         </li>
//         <li>
//           <button 
//             onClick={() => handleRoleSelect('Admin')} 
//             className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
//           >
//             Admin
//           </button>
//         </li>
//         <li>
//           <button 
//             onClick={() => handleRoleSelect('User')} 
//             className="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white"
//           >
//             User
//           </button>
//         </li>
//       </ul>
//     </div>
//   )}
// </div>











